#!/bin/bash
# ============================================================================
# NGS Pipeline - Report Generation Step
# Generates summary report of the analysis
# ============================================================================
set -euo pipefail

echo "=========================================="
echo "  REPORT GENERATION"
echo "  $(date)"
echo "=========================================="

REPORT_DIR="${NGS_RESULTS_DIR}/report"
mkdir -p "${REPORT_DIR}"

REPORT_FILE="${REPORT_DIR}/analysis_report.html"

# Collect stats
TOTAL_SAMPLES=$(echo "${NGS_SAMPLE_R1}" | tr ',' '\n' | wc -l | tr -d ' ')

# Count variants if VCF files exist
TOTAL_VARIANTS=0
if [ -f "${NGS_RESULTS_DIR}/.variant_vcfs.txt" ]; then
    VCF_LIST=$(cat "${NGS_RESULTS_DIR}/.variant_vcfs.txt")
    IFS=',' read -ra VCF_FILES <<< "${VCF_LIST}"
    for vcf in "${VCF_FILES[@]}"; do
        if command -v ${BCFTOOLS_PATH:-bcftools} &>/dev/null && [ -f "${vcf}" ]; then
            count=$(${BCFTOOLS_PATH:-bcftools} view -H "${vcf}" 2>/dev/null | wc -l | tr -d ' ')
            TOTAL_VARIANTS=$((TOTAL_VARIANTS + count))
        fi
    done
fi

# Collect alignment stats
ALIGN_STATS=""
if [ -d "${NGS_RESULTS_DIR}/alignment" ]; then
    for flagstat in "${NGS_RESULTS_DIR}"/alignment/*.flagstat.txt; do
        if [ -f "${flagstat}" ]; then
            sample_name=$(basename "${flagstat}" .flagstat.txt)
            mapped=$(grep "mapped (" "${flagstat}" | head -1 | cut -d' ' -f1)
            total=$(grep "in total" "${flagstat}" | head -1 | cut -d' ' -f1)
            ALIGN_STATS="${ALIGN_STATS}<tr><td>${sample_name}</td><td>${total}</td><td>${mapped}</td></tr>"
        fi
    done
fi

# Generate HTML report
cat > "${REPORT_FILE}" <<REPORT_HTML
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>NGS Analysis Report</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 900px; margin: 40px auto; padding: 0 20px; color: #333; }
  h1 { color: #1a73e8; border-bottom: 2px solid #1a73e8; padding-bottom: 10px; }
  h2 { color: #444; margin-top: 30px; }
  table { border-collapse: collapse; width: 100%; margin: 15px 0; }
  th, td { border: 1px solid #ddd; padding: 10px 14px; text-align: left; }
  th { background: #f5f5f5; font-weight: 600; }
  tr:nth-child(even) { background: #fafafa; }
  .stat-box { display: inline-block; background: #e8f0fe; padding: 15px 25px; border-radius: 8px; margin: 5px 10px 5px 0; }
  .stat-box .value { font-size: 28px; font-weight: bold; color: #1a73e8; }
  .stat-box .label { font-size: 13px; color: #666; }
  .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; color: #888; font-size: 12px; }
</style>
</head>
<body>
<h1>NGS Analysis Report</h1>
<p><strong>Date:</strong> $(date)</p>
<p><strong>Analysis Type:</strong> ${NGS_ANALYSIS_TYPE}</p>
<p><strong>Run Mode:</strong> ${NGS_RUN_MODE}</p>
<p><strong>Threads:</strong> ${NGS_THREADS} | <strong>Memory:</strong> ${NGS_MEMORY_GB} GB</p>

<h2>Summary</h2>
<div>
  <div class="stat-box"><div class="value">${TOTAL_SAMPLES}</div><div class="label">Samples</div></div>
  <div class="stat-box"><div class="value">${TOTAL_VARIANTS}</div><div class="label">Variants Called</div></div>
</div>

<h2>Alignment Statistics</h2>
<table>
<tr><th>Sample</th><th>Total Reads</th><th>Mapped Reads</th></tr>
${ALIGN_STATS:-<tr><td colspan="3">No alignment data available</td></tr>}
</table>

<h2>Output Files</h2>
<table>
<tr><th>Directory</th><th>Contents</th></tr>
<tr><td>qc/</td><td>FastQC and MultiQC quality reports</td></tr>
<tr><td>trimmed/</td><td>Adapter-trimmed reads and fastp reports</td></tr>
<tr><td>alignment/</td><td>Sorted, deduplicated BAM files and statistics</td></tr>
<tr><td>variants/</td><td>Raw and filtered VCF files</td></tr>
<tr><td>annotation/</td><td>Annotated variant files</td></tr>
<tr><td>report/</td><td>This summary report</td></tr>
</table>

<div class="footer">
  Generated by NGS Analysis Platform v1.0.0
</div>
</body>
</html>
REPORT_HTML

echo "[REPORT] HTML report generated: ${REPORT_FILE}"

# Update summary files
echo "" >> "${NGS_RESULTS_DIR}/qc_summary.txt"
echo "Total variants called: ${TOTAL_VARIANTS}" >> "${NGS_RESULTS_DIR}/qc_summary.txt"

echo "[REPORT] Report generation completed successfully"
